### ISSUE TITLE
Examples and WMS precipitation forecasts

### ISSUE THREAD

**Issue by braincow** [fmidev/metoclient#54]
FMI has removed apparently the preicipation forecast model from their WMS service. I inquiried about this few months back on Twitter and their response was that they have transitioned to a new model.

How can we use this new model, HARMONIE(?) I believe, with metoclient so that we can again get the precipation forecasts on the map?

**Comment by TheKarppinen** [comment]
You may use FMI helpdesk form in the end of the FMI [web page](https://www.ilmatieteenlaitos.fi/tukipyynto-avoimesta-datasta) to ask information about open data and for example which WMS content could be used in this case.

Currently available open data is also mentioned [here](https://www.ilmatieteenlaitos.fi/avoin-data-avattavat-aineistot).

**Comment by braincow** [comment]
Funny thing is that I already did that too (in finnish, sorry):

"Meteoclientista en tiedä mitään ja sen ylläpidon seuraaminen ei kuulu avoimen datan helpdeskiin, mutta laitan jollekulle sopivalle uhrille siitä, että päivittäisivät ohjeet. Ohjeiden osalta yleensä ottaen ei päivityksiä ole vielä tehty."

Im not that literate in the entire WMS ecosystem and to a novice it has extremily steep learning curve and thus I rely on the examples in your great tool. So having an working example to replace the old model that is now defunct would be appriciated.

**Comment by TheKarppinen** [comment]
I agree that learning curve can be quite steep with this open data and open source ensemble and examples are good way to get started quickly.

Metoclient (open source) itself does not belong to open data helpdesk responsibility area. But, metoclient can use open data web service interfaces. And, opendata helpdesk should provide the information about the open data content. For example in this case which data (if any) could be used from the new model to get the precipitation forecast content via WMS.

Just in case, I can also check from the helpdesk if new precipitation forecast layer is already available or if there are already any plans to provide it in the near future. I'll inform here when I get more information about this.

**Comment by TheKarppinen** [comment]
I was informed that the precipitation-forecast WMS layer was based on legacy production before. That production has also been removed now. New replacing production for this layer has not been planned for now. Therefore, open data can not provide new precipitation-forecast WMS layer either. And so, we can not give a similar forecast layer as an example configuration for metoclient here. Notice, FMI also provides paid customer WMS and similar web services, for example, for broader data selections, but they can not be used as open data examples here. But, those paid services might be useful if you are building for example business based on this kind of services.
